name: Build

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: | 
        dotnet build --configuration Release --no-restore
        dotnet pack -c Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal