name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest
    
    env:
      VERSION: ${{ github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      run: |
        echo "Building with ${{ env.VERSION }}"
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: | 
        dotnet build --configuration Release --no-restore -p:Version=${{ env.VERSION }}
        dotnet pack --output nupkgs -c Release -p:Version=${{ env.VERSION }}
          
    - name: Publish to NuGet
      run: |
        dotnet nuget push nupkgs\*.nupkg -k ${{ secrets.NUGET_TOKEN }}  --source https://api.nuget.org/v3/index.json
